# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VUser-Google-ProvisioningAPI
version:      0.22
version_from: lib/VUser/Google/ProvisioningAPI.pm
installdirs:  site
requires:
    Carp:                          0
    Encode:                        0
    HTTP::Request:                 0
    LWP::UserAgent:                0
    XML::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
